name: Welfare Claim Lucky Coin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Welfare Claim Lucky Coin Script
        run: python welfare_lucky_coin.py
        env:
          SCKEY: ${{ secrets.SCKEY }}
          WELFARE_UID: ${{ secrets.WELFARE_UID }}
          WELFARE_SCENE: ${{ secrets.WELFARE_SCENE }}
          WELFARE_TOKEN: ${{ secrets.WELFARE_TOKEN }}
          WELFARE_TEMPLATE1: ${{ secrets.WELFARE_TEMPLATE1 }}
          WELFARE_TEMPLATE2: ${{ secrets.WELFARE_TEMPLATE2 }}